export const techMap: { [key: string]: string } = {
  // --- Languages ---
  javascript: "devicon-javascript-plain",
  js: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  ts: "devicon-typescript-plain",
  python: "devicon-python-plain",
  py: "devicon-python-plain",
  java: "devicon-java-plain",
  c: "devicon-c-plain",
  cplusplus: "devicon-cplusplus-plain",
  cpp: "devicon-cplusplus-plain",
  csharp: "devicon-csharp-plain",
  cs: "devicon-csharp-plain",
  go: "devicon-go-original-wordmark",
  golang: "devicon-go-original-wordmark",
  rust: "devicon-rust-plain",
  php: "devicon-php-plain",
  ruby: "devicon-ruby-plain",
  swift: "devicon-swift-plain",
  kotlin: "devicon-kotlin-plain",
  dart: "devicon-dart-plain",

  // --- Frontend Frameworks & Libs ---
  react: "devicon-react-original",
  nextjs: "devicon-nextjs-original",
  next: "devicon-nextjs-original",
  vuejs: "devicon-vuejs-plain",
  vue: "devicon-vuejs-plain",
  angular: "devicon-angular-plain",
  svelte: "devicon-svelte-plain",
  html5: "devicon-html5-plain",
  html: "devicon-html5-plain",
  css3: "devicon-css3-plain",
  css: "devicon-css3-plain",
  sass: "devicon-sass-original",
  tailwindcss: "devicon-tailwindcss-original",
  tailwind: "devicon-tailwindcss-original",
  bootstrap: "devicon-bootstrap-plain",
  materialui: "devicon-materialui-plain",
  mui: "devicon-materialui-plain",
  redux: "devicon-redux-original",
  jquery: "devicon-jquery-plain",
  astro: "devicon-astro-plain",

  // --- Backend & Runtime ---
  nodejs: "devicon-nodejs-plain",
  node: "devicon-nodejs-plain",
  express: "devicon-express-original",
  nestjs: "devicon-nestjs-plain",
  django: "devicon-django-plain",
  flask: "devicon-flask-original",
  spring: "devicon-spring-original",
  laravel: "devicon-laravel-plain",
  dotnetcore: "devicon-dotnetcore-plain",
  dotnet: "devicon-dot-net-plain",

  // --- Databases (Your MERN/SQL Focus) ---
  mongodb: "devicon-mongodb-plain",
  mongo: "devicon-mongodb-plain",
  postgresql: "devicon-postgresql-plain",
  postgres: "devicon-postgresql-plain",
  mysql: "devicon-mysql-plain",
  mariadb: "devicon-mariadb-plain",
  sqlite: "devicon-sqlite-plain",
  redis: "devicon-redis-plain",
  firebase: "devicon-firebase-plain",
  supabase: "devicon-supabase-plain",
  prisma: "devicon-prisma-original",
  elasticsearch: "devicon-elasticsearch-plain",

  // --- DevOps, Cloud & Tools ---
  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  k8s: "devicon-kubernetes-plain",
  git: "devicon-git-plain",
  github: "devicon-github-original",
  gitlab: "devicon-gitlab-plain",
  bitbucket: "devicon-bitbucket-original",
  linux: "devicon-linux-plain",
  ubuntu: "devicon-ubuntu-plain",
  bash: "devicon-bash-plain",
  nginx: "devicon-nginx-original",
  apache: "devicon-apache-plain",
  amazonwebservices: "devicon-amazonwebservices-plain-wordmark",
  aws: "devicon-amazonwebservices-plain-wordmark",
  googlecloud: "devicon-googlecloud-plain",
  gcp: "devicon-googlecloud-plain",
  azure: "devicon-azure-plain",
  vercel: "devicon-vercel-original",
  netlify: "devicon-netlify-plain",
  heroku: "devicon-heroku-original",

  // --- Design & Other ---
  figma: "devicon-figma-plain",
  vscode: "devicon-vscode-plain",
  jest: "devicon-jest-plain",
  npm: "devicon-npm-original-wordmark",
  yarn: "devicon-yarn-plain",
  webpack: "devicon-webpack-plain",
  vite: "devicon-vitejs-plain",
  graphql: "devicon-graphql-plain",
};
